enum BasicOperations {
    STATUS,
    PARK,
    LEAVE,
    CREATE_PARKING_LOT
}


enum AdvancedOperations {
    REGISTRATION_NUMBERS_FOR_CARS_WITH_COLOUR,
    SLOT_NUMBERS_FOR_CARS_WITH_COLOUR,
    SLOT_NUMBER_FOR_REGISTRATION_NUMBER,
}
